baseURL = 'https://bleauweb.net/'
languageCode = 'en-us'
title = 'BleauWeb'
theme = "github-style"

[params]
    author = "Brandon Bleau"
    description = ""
    github = "bmbleau"
    mastodonUsername = "@mxbleau"
    mastodonWebsite = "mastodon.social"
    linkedin = "brandon-bleau"
    instagram = "mx_bleau"
    email = "bmbleau@gmail.com"
    url = "https://bleauweb.net"
    keywords = "blog, google analytics"
    rss = true
    lastmod = true
    userStatusEmoji = "💡"
    favicon = "/images/github.png"
    avatar = "/images/IMG_0068.jpeg"
    headerIcon = "/images/thinking.png"
    location = "USA, Earth"
    enableGitalk = false